name: odacova
favicon: null
layout_spectrum: 0.41558
typography_spectrum: 0.27157
title: A Love Letter To The Modern Hustle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7cc2bb'
    - '#3185e6'
    - '#030303'
    - '#fefefe'
    - '#404508'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
